mod.mc_compat=>=1.21.9 <=1.21.10
mod.mc_releases=1.21.10
mod.mc_publish=1.21.9,1.21.10

deps.fabric_loader=0.19.3
deps.fabric_api=0.138.3+1.21.10
deps.flashback=0.39.7
deps.hdr_mod=JaQ5khlL

deps.sodium=mc1.21.10-0.7.3-fabric
deps.iris=1.9.7+1.21.10-fabric

# for hdr mod
deps.cloth_config=20.0.149
deps.architectury=18.0.8

loomx.loom_version=1.17-SNAPSHOT
